// This file is generated by Fumadocs during build
export const map = {
  'introduction': {
    title: 'Introduction',
    description: 'Introduction to ForteUI',
    _exports: {
      default: () => import('../../content/docs/introduction.mdx'),
    },
  },
  'getting-started': {
    title: 'Getting Started', 
    description: 'Get started with ForteUI',
    _exports: {
      default: () => import('../../content/docs/getting-started.mdx'),
    },
  },
};
